### PR TITLE
added header improvements

### PR DESCRIPTION
**Pull request by yuvraj-wale**
fixed the issue #14 , do merge the PR as soon as possible. Thanks :)

### CODE REVIEW

**Comment by shriya-tiwari** [comment]
can you change the colour of the header so as to suit the theme of the website because it is currently looking really out of place, and also the font is a bit different. I like the design nice, but please make the changes at the earliest so i can merge your PR

**Comment by yuvraj-wale** [comment]
yeah, I will  surely make the changes, could you specify which colour you would like ?

**Comment by yuvraj-wale** [comment]
hey, I made all the changes requested : change of colour and font ,header now spanning the whole length and also added a yellow separator line which is frequently used in the website. Do let me know if any more changes needed else waiting for the merge. Thanks :)

**Comment by shriya-tiwari** [comment]
Great work!!! 
The website looks so much better now 😃

**Pull request merged**
