### PR TITLE
added animations and dark mode

### PR DESCRIPTION
**Pull request by khushigarg1**
added some text animations, hover effects for submit button and dark mode.

### CODE REVIEW

**Comment by shriya-tiwari** [comment]
Great work, but the recent pull request that i merged had removed alerts and added snackbars. I can see in changes that you have removed the snackbars from the code, please add them and bring the website to the previous state and then create a new pull request with your added code.

**Comment by khushigarg1** [comment]
Okay I will do that Thank you.

**Comment by khushigarg1** [comment]
should i change hover effect of submit button?

**Comment by khushigarg1** [comment]
Should i remove hover effect of submit button?

**Comment by shriya-tiwari** [comment]
> Should i remove hover effect of submit button?

No the hover effect is fine, just change the color such that the submit button matches the theme and colors of the website, the rainbow effect is not going along that well with the website and the black color of the submit button as well.

**Comment by khushigarg1** [comment]
I have changed black color of submit button.

**Comment by shriya-tiwari** [comment]
I still cant see the snackbars, please add the div of snackbar that was present in index.html and the function enableSnackbar in index.js. You can refer the changes that you need to make from the 'files changed' option.

**Comment by shriya-tiwari** [comment]
Refer to the changes that issue no. #11 has done and ensure that they are present.

**Comment by khushigarg1** [comment]
Sorry, Now I have added snackbar.

**Comment by shriya-tiwari** [comment]
Great work @khushigarg1

**Comment by khushigarg1** [comment]
Thank You!!

**Pull request merged**
